options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        vmlist=$(gcloud compute instances list --format='value(name)' --filter="labels.app:loserbot AND status:RUNNING") && for vm in $vmlist; do echo $vm && gcloud compute ssh cloudbuild@$vm --zone $(gcloud compute instances list --format='value(zone)' --filter="name='$vm'") --quiet -- 'rm -rf LoserBot && git clone https://github.com/Kaushik-Pahuja-Portfolio/LoserBot && pip install -r LoserBot/requirements.txt && nohup python3 LoserBot/LoserBot.py && exit'; done
    entrypoint: bash